name: 'owocto spowork'
description: 'Says owo to you'
inputs:
  who-to-owo:  # id of input
    description: 'Who to owo at'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we owoed at you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-owo }}
