name: 'owocto spowork'
description: 'Outputs encourages messages to you'
inputs:
  user:  # id of input
    description: 'User to encourage'
    required: true
    default: 'everyone'
outputs:
  time: # id of output
    description: 'Time of message output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
