on: [push]

jobs:
  owo_job:
    runs-on: ubuntu-latest
    name: Encouraging message
    steps:
    - name: owo action step
      id: owo
      uses: phisv/crispy-octo-spork@master
      with:
        user: 'phisv'
    - name: output time
      run: echo "The time was ${{ steps.owo.outputs.time }}"
